fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -144,14 +144,14 @@ jobs:
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
               --tags project=udacity
 
-      # - run:
-      #     name: Ensure front-end infrastructure exist
-      #     command: |
-      #       aws cloudformation deploy \
-      #         --template-file .circleci/files/frontend.yml \
-      #         --tags project=hey \
-      #           --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"  \
-      #           --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --tags project=hey \
+                --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"  \
+                --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
 
       - run:
           name: Add back-end ip to ansible inventory
@@ -269,8 +269,11 @@ jobs:
           name: Deploy frontend objects
           command: |
             # your code here
-            aws s3 cp ./frontend/dist s3://udapeople-51fa95d/ --recursive
-
+            cd frontend
+            rm -rf node_modules
+            npm install
+            npm run build
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
   deploy-backend:
     docker:
       - image: python:3.7-alpine3.11
@@ -332,29 +335,47 @@ jobs:
 
       # Here's where you will add some code to rollback on failure
 
-  #   smoke-test:
-  #     docker:
-  #       # Lightweight Docker image
-  #     steps:
-  #       # Checkout code from git
-  #       - run:
-  #           name: Install dependencies
-  #           command: |
-  #             # your code here
-  #       - run:
-  #           name: Get backend url
-  #           command: |
-  #             # your code here
-  #       - run:
-  #           name: Backend smoke test.
-  #           command: |
-  #             # your code here
-  #       - run:
-  #           name: Frontend smoke test.
-  #           command: |
-  #             # your code here
-  #       # Here's where you will add some code to rollback on failure
+    smoke-test:
+      docker:
+        - image: python:3.7-alpine3.11
+      steps:
+        # Checkout code from git
+        - checkout
+        - run:
+            name: Install dependencies
+            command: |
+              pip3 install awscli
+              apk add --update curl
+        - run:
+            name: Get backend url
+            command: |
+              export BACKEND_URL=$(aws ec2 describe-instances      --query 'Reservations[*].Instances[*].PublicDnsName' --filters 'Name=tag:project,Values=*' --output text)
 
+        - run:
+            name: Backend smoke test.
+            command: |
+
+              if curl "${BACKEND_UR}L/api/status" | grep "ok"
+              then
+                  exit 0
+              else
+                  exit 1
+              fi
+        - run:
+            name: Frontend smoke test.
+            command: |
+              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
+                  echo ${URL}
+                  if curl -s ${URL} | grep "Welcome"
+                  then
+                      # Change this to 0 after the job fails
+                    exit 0
+                  else
+                    exit 1
+                  fi
+        # Here's where you will add some code to rollback on failure
+
+      # Here's where you will add some code to rollback on failure
   #   cloudfront-update:
   #     docker:
   #       # Docker image here that supports AWS CLI
@@ -411,8 +432,8 @@ workflows:
           requires: [deploy-infrastructure]
       - run-migrations:
           requires: [configure-infrastructure]
-      # - deploy-frontend
-      #     requires: [run-migrations]
+      - deploy-frontend:
+          requires: [run-migrations]
       - deploy-backend:
           requires: [configure-infrastructure]
       #     requires: [run-migrations]
