fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -356,24 +356,24 @@ jobs:
           command: |
             echo ${BACKEND_UR}
 
-            #  if curl "http://${BACKEND_UR}/api/status" | grep "ok"
-            #  then
-            #      exit 0
-            #  else
-            #      exit 1
-            #  fi
+             if curl "http://${BACKEND_UR}/api/status" | grep "ok"
+             then
+                 exit 0
+             else
+                 exit 1
+             fi
       - run:
           name: Frontend smoke test.
           command: |
-            # URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
-            #     echo ${URL}
-            #     if curl -s ${URL} | grep "Welcome"
-            #     then
-            #         # Change this to 0 after the job fails
-            #       exit 0
-            #     else
-            #       exit 1
-            #     fi
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
+                echo ${URL}
+                if curl -s ${URL} | grep "Welcome"
+                then
+                    # Change this to 0 after the job fails
+                  exit 0
+                else
+                  exit 1
+                fi
         # Here's where you will add some code to rollback on failure
 
       # Here's where you will add some code to rollback on failure
